class ResourceAlreadyExist(Exception):
    pass

class ResourceNotFound(Exception):
    pass

